### ISSUE TITLE
AAA Accepting special characters

### ISSUE THREAD

**Issue by neilkyoung** [gaarutyunov/ts-input-mask#8]
It seems that using the input mask to restrict a user to enter only a-z or A-Z characters means that a user can still enter special characters into the input field. Should it only accept a-z or A-Z for keyboard entry? It seems that using AAA means that the user has to enter three mandatory characters but special characters can also be a valid input.

Would a custom notation be needed if we wanted to restrict keyboard entry to just a-z or A-Z characters?

**Comment by gaarutyunov** [comment]
I am deeply sorry for not responding for so long. Developed the library for one use case and stopped supporting it. Fixed in version 2.1.0. There was a mistake in RegExp.
